CREATE TABLE yellow_tripdata (
    "VendorID" INTEGER,
    "tpep_pickup_datetime" TIMESTAMP,
    "tpep_dropoff_datetime" TIMESTAMP,
    "passenger_count" INTEGER,
    "trip_distance" NUMERIC,
    "RatecodeID" INTEGER,
    "store_and_fwd_flag" TEXT,
    "PULocationID" INTEGER,
    "DOLocationID" INTEGER,
    "payment_type" INTEGER,
    "fare_amount" NUMERIC,
    "extra" NUMERIC,
    "mta_tax" NUMERIC,
    "tip_amount" NUMERIC,
    "tolls_amount" NUMERIC,
    "improvement_surcharge" NUMERIC,
    "total_amount" NUMERIC,
    "congestion_surcharge" NUMERIC,
    "Airport_fee" NUMERIC,
    "cbd_congestion_fee" NUMERIC
);

CREATE TABLE green_tripdata (
    "VendorID" INTEGER,
    "lpep_pickup_datetime" TIMESTAMP,
    "lpep_dropoff_datetime" TIMESTAMP,
	"store_and_fwd_flag" TEXT,
	"RatecodeID" INTEGER,
	"PULocationID" INTEGER,
    "DOLocationID" INTEGER,
    "passenger_count" INTEGER,
    "trip_distance" NUMERIC,
	"fare_amount" NUMERIC,
	"extra" NUMERIC,
	"mta_tax" NUMERIC,
	"tip_amount" NUMERIC,
	"tolls_amount" NUMERIC,
	"ehail_fee" NUMERIC,
    "improvement_surcharge" NUMERIC,
    "total_amount" NUMERIC,	
    "payment_type" INTEGER,
	"trip_type" NUMERIC,
    "congestion_surcharge" NUMERIC,
    "cbd_congestion_fee" NUMERIC
);